version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    volumes:
      - .:/var/www/app
    working_dir: /var/www/app
    depends_on:
      - db
    environment:
      DATABASE_URL: "pgsql://app:app@db:5432/guard"
    networks:
      - symfony

  db:
    image: postgis/postgis:16-3.3
    container_name: symfony_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: guard
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - symfony

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony

volumes:
  db_data:

networks:
  symfony:
