version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    volumes:
      - .:/var/www/app
    env_file:
      - .env
    working_dir: /var/www/app
    depends_on:
      - db
      - mercure
    environment:
      DATABASE_URL: "pgsql://app:app@db:5432/guard"
      MERCURE_URL: "http://mercure/.well-known/mercure"
      MERCURE_JWT_TOKEN: "a-string-secret-at-least-256-bits-long"
    networks:
      - symfony

  db:
    image: postgis/postgis:16-master
    container_name: symfony_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: guard
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/db/init-postgis:/docker-entrypoint-initdb.d
    networks:
      - symfony

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony

  mercure:
    image: dunglas/mercure
    container_name: symfony_mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: "a-string-secret-at-least-256-bits-long"
      MERCURE_SUBSCRIBER_JWT_KEY: "a-string-secret-at-least-256-bits-long"
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
        anonymous 1
    ports:
      - "3000:80"
    networks:
      - symfony

volumes:
  db_data:

networks:
  symfony:
    driver: bridge