parameters:
    agent_pictures_directory: '%kernel.project_dir%/public/uploads/agents'
    mercure_jwt_token: '%env(MERCURE_JWT_PUBLISHER)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    mercure.jwt_provider:
        class: Symfony\Component\Mercure\Jwt\StaticTokenProvider
        arguments:
            - '%mercure_jwt_token%'

    Symfony\Component\Mercure\HubInterface:
        class: Symfony\Component\Mercure\Hub
        arguments:
            - '%env(MERCURE_URL)%'
            - '@mercure.jwt_provider'
    
    App\Service\CryptService:
        arguments:
            $appSecret: '%env(APP_SECRET)%'

    App\Service\MercureTokenGenerator:
        arguments:
            $mercureJwtSecret: '%env(MERCURE_JWT_SECRET)%'

    # JWT Authentication Event Listeners
    App\EventListener\JwtLoginSuccessHandler:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccess }
    
    App\EventListener\JwtLoginFailureHandler:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailure }
            
    # Contrôleurs invokables SOLID pour AdminAgent
    App\Controller\AdminAgent\:
        resource: '../src/Controller/AdminAgent/'
        public: true
        tags: ['controller.service_arguments']

    # Contrôleurs invokables SOLID pour Client
    App\Controller\Client\:
        resource: '../src/Controller/Client/'
        public: true
        tags: ['controller.service_arguments']

    # Contrôleurs invokables SOLID pour Agent
    App\Controller\Agent\:
        resource: '../src/Controller/Agent/'
        public: true
        tags: ['controller.service_arguments']
        
    # Contrôleurs invokables SOLID pour User
    App\Controller\User\:
        resource: '../src/Controller/User/'
        public: true
        tags: ['controller.service_arguments']

    # Contrôleurs invokables SOLID pour Message
    App\Controller\Message\:
        resource: '../src/Controller/Message/'
        public: true
        tags: ['controller.service_arguments']

    # Contrôleurs invokables SOLID pour ResetPassword
    App\Controller\ResetPassword\:
        resource: '../src/Controller/ResetPassword/'
        public: true
        tags: ['controller.service_arguments']
