parameters:
    mercure_jwt_token: '%env(MERCURE_JWT_PUBLISHER)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    mercure.jwt_provider:
        class: Symfony\Component\Mercure\Jwt\StaticTokenProvider
        arguments:
            - '%mercure_jwt_token%'

    Symfony\Component\Mercure\HubInterface:
        class: Symfony\Component\Mercure\Hub
        arguments:
            - '%env(MERCURE_PUBLISH_URL)%'
            - '@mercure.jwt_provider'
    
    App\Service\CryptService:
        arguments:
            $appSecret: '%env(APP_SECRET)%'

    App\Service\MercureTokenGenerator:
        arguments:
            $mercureJwtSecret: '%env(MERCURE_JWT_SECRET)%'

    # JWT Authentication Event Listeners
    App\EventListener\JwtLoginSuccessHandler:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccess }
    
    App\EventListener\JwtLoginFailureHandler:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailure }
