parameters:
    # Ici tu peux définir tes paramètres personnalisés si besoin

services:
    # Configuration par défaut pour tous les services
    _defaults:
        autowire: true      # injection automatique des dépendances
        autoconfigure: true # auto-ajout de tags selon interface/type

    # Rend toutes les classes du dossier src/ disponibles comme services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    # Déclaration explicite des repositories Doctrine comme services avec tag obligatoire
    App\Repository\:
        resource: '../src/Repository'
        tags: ['doctrine.repository_service']
        autowire: true
        autoconfigure: true

    # Déclaration explicite du listener JWT avec méthode obligatoire
    App\EventListener\JWTCreatedListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    # Ajout explicite de AuthController pour qu'il soit public et tagué
    App\Controller\AuthController:
        public: true
        tags: ['controller.service_arguments']
